"""add workspaces, users, and workspace_id scoping

Revision ID: 04cef0ef5c73
Revises: 54c6afa00b05
Create Date: 2026-08-22 12:27:14.396623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04cef0ef5c73'
down_revision: Union[str, None] = '54c6afa00b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspaces_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_users_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_alerts_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_alerts_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_forecasts_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_forecasts_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_inventory_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_inventory_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_products_sku', type_='unique')
        batch_op.create_index(batch_op.f('ix_products_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_unique_constraint('uq_product_workspace_sku', ['workspace_id', 'sku'])
        batch_op.create_foreign_key(batch_op.f('fk_products_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('replenishment_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_replenishment_recommendations_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_replenishment_recommendations_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_shipments_shipment_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_shipments_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_unique_constraint('uq_shipment_workspace_number', ['workspace_id', 'shipment_number'])
        batch_op.create_foreign_key(batch_op.f('fk_shipments_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('simulation_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_simulation_scenarios_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_simulation_scenarios_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_suppliers_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_suppliers_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('uq_warehouses_code', type_='unique')
        batch_op.create_index(batch_op.f('ix_warehouses_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_unique_constraint('uq_warehouse_workspace_code', ['workspace_id', 'code'])
        batch_op.create_foreign_key(batch_op.f('fk_warehouses_workspace_id_workspaces'), 'workspaces', ['workspace_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_warehouses_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_constraint('uq_warehouse_workspace_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_warehouses_workspace_id'))
        batch_op.create_unique_constraint('uq_warehouses_code', ['code'])
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_suppliers_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suppliers_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('simulation_scenarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_simulation_scenarios_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_simulation_scenarios_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shipments_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_constraint('uq_shipment_workspace_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_shipments_workspace_id'))
        batch_op.create_unique_constraint('uq_shipments_shipment_number', ['shipment_number'])
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('replenishment_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_replenishment_recommendations_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_replenishment_recommendations_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_constraint('uq_product_workspace_sku', type_='unique')
        batch_op.drop_index(batch_op.f('ix_products_workspace_id'))
        batch_op.create_unique_constraint('uq_products_sku', ['sku'])
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forecasts_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_forecasts_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alerts_workspace_id_workspaces'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_slug'))
        batch_op.drop_index(batch_op.f('ix_workspaces_id'))

    op.drop_table('workspaces')
    # ### end Alembic commands ###
