"""add is_estimated flag to demand_records

Revision ID: a9c4e1b7d208
Revises: 04cef0ef5c73
Create Date: 2026-09-25 10:14:02.118294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c4e1b7d208'
down_revision: Union[str, None] = '04cef0ef5c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL with a server default so existing rows (seeded demo demand)
    # backfill to False instead of failing the ALTER.
    with op.batch_alter_table('demand_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_estimated', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_records', schema=None) as batch_op:
        batch_op.drop_column('is_estimated')
    # ### end Alembic commands ###
